name: Python linting
on: [push, pull_request]
jobs:
  test:
    name: Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
