name: Python linting
on: [push, pull_request]
jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Flake
        run: pip install flake8
      - name: Run Flake
        run: flake8 anyblok --exclude=*/tests/*
