name: Tests framework for MySQL
on: 
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: sqlalchemy_utils_test
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install graphviz package
        run: bash .ci/install_graphviz.sh
      - name: Install Wheel
        run: pip install -U pip wheel
      - name: Install mysqlclient
        run: pip install mysqlclient
      - name: Install pytest
        run: pip install pytest pytest-cov mock
      - name: Install extra dependencies
        run: pip install colour passlib furl phonenumbers pycountry cryptography
      - name: Install AnyBlok
        run: pip install .
      - name: Run tests
        env:
          ANYBLOK_DATABASE_DRIVER: mysql
          ANYBLOK_DATABASE_NAME: sqlalchemy_utils_test
          ANYBLOK_DATABASE_PORT: 3306
          ANYBLOK_DATABASE_HOST: localhost
        run: pytest --cov=anyblok anyblok/tests/test_authorization.py
