name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        python-version: ['3.10']
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sqlalchemy_utils_test
        # Set health checks to wait until PostgreSQL has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install graphviz package
        run:
          - sudo apt-get update
          - sudo apt-get install graphviz
      - name: Install python dependencies
        run:
          - pip install
          - pip install wheel
          - pip install sqlalchemy
          - pip install psycopg2
          - pip install pytest
          - pip install pytest-cov
          - pip install colour
          - pip install passlib
          - pip install furl
          - pip install phonenumbers
          - pip install pycountry
          - pip install cryptography
          - pip install .
      - name: Run tests
        env:
          ANYBLOK_DATABASE_DRIVER: postgresql
          ANYBLOK_DATABASE_NAME: sqlalchemy_utils_test
        run: pytest --cov=anyblok anyblok/tests
