name: Tests
on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  Postgres:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install postgres package
        run: bash .ci/install_postgres.sh
      - name: Install graphviz package
        run: bash .ci/install_graphviz.sh
      - name: Install Wheel
        run: pip install -U pip wheel
      - name: Install psycopg2-binary
        run: pip install psycopg2-binary
      - name: Install pytest
        run: pip install pytest pytest-cov mock coverage-lcov
      - name: Install extra dependencies
        run: pip install colour passlib furl phonenumbers pycountry cryptography
      - name: Install AnyBlok
        run: pip install .
      - name: Run framework tests
        env:
          ANYBLOK_DATABASE_DRIVER: postgresql
          ANYBLOK_DATABASE_NAME: anyblok_test_${{ github.run_id }}-${{ matrix.python-version }}
          ANYBLOK_DATABASE_PORT: 5432
          ANYBLOK_DATABASE_HOST: github-action-runner.famille-suzanne.fr
          ANYBLOK_DATABASE_USER: postgres
          ANYBLOK_DATABASE_PASSWORD: postgres
        run: pytest anyblok/tests/test_authorization.py
      - name: Drop db
        env:
          PGHOST: github-action-runner.famille-suzanne.fr
          PGPASSWORD: postgres
          PGPORT: 5432
        run: dropdb -U postgres anyblok_test_${{ github.run_id }}-${{ matrix.python-version }}
      - name: Run anyblok_createdb
        env:
          ANYBLOK_DATABASE_DRIVER: postgresql
          ANYBLOK_DATABASE_NAME: anyblok_test_${{ github.run_id }}-${{ matrix.python-version }}
          ANYBLOK_DATABASE_PORT: 5432
          ANYBLOK_DATABASE_HOST: github-action-runner.famille-suzanne.fr
          ANYBLOK_DATABASE_USER: postgres
          ANYBLOK_DATABASE_PASSWORD: postgres
        run: anyblok_createdb --install-all-bloks  --with-demo
      - name: Run anyblok_updatedb
        env:
          ANYBLOK_DATABASE_DRIVER: postgresql
          ANYBLOK_DATABASE_NAME: anyblok_test_${{ github.run_id }}-${{ matrix.python-version }}
          ANYBLOK_DATABASE_PORT: 5432
          ANYBLOK_DATABASE_HOST: github-action-runner.famille-suzanne.fr
          ANYBLOK_DATABASE_USER: postgres
          ANYBLOK_DATABASE_PASSWORD: postgres
        run: anyblok_updatedb --update-all-bloks
      - name: Run bloks tests
        env:
          ANYBLOK_DATABASE_DRIVER: postgresql
          ANYBLOK_DATABASE_NAME: anyblok_test_${{ github.run_id }}-${{ matrix.python-version }}
          ANYBLOK_DATABASE_PORT: 5432
          ANYBLOK_DATABASE_HOST: github-action-runner.famille-suzanne.fr
          ANYBLOK_DATABASE_USER: postgres
          ANYBLOK_DATABASE_PASSWORD: postgres
        run: pytest --cov-append anyblok/bloks/anyblok_core
      - name: Generate lcov
        run: coverage-lcov
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: ${{ github.job }}
          path-to-lcov: lcov.info

  MySQL:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install mysql package
        run: bash .ci/install_mysql.sh
      - name: Install graphviz package
        run: bash .ci/install_graphviz.sh
      - name: Install Wheel
        run: pip install -U pip wheel
      - name: Install mysqlclient
        run: pip install mysqlclient
      - name: Install pytest
        run: pip install pytest pytest-cov mock coverage-lcov
      - name: Install extra dependencies
        run: pip install colour passlib furl phonenumbers pycountry cryptography
      - name: Install AnyBlok
        run: pip install .
      - name: Run Framworks tests
        env:
          ANYBLOK_DATABASE_DRIVER: mysql
          ANYBLOK_DATABASE_NAME: anyblok_test_${{ github.run_id }}
          ANYBLOK_DATABASE_PORT: 3306
          ANYBLOK_DATABASE_HOST: github-action-runner.famille-suzanne.fr
          ANYBLOK_DATABASE_USER: root
          ANYBLOK_DATABASE_PASSWORD: rootpassword
        run: pytest anyblok/tests/test_authorization.py
      - name: Drop db
        env:
          MYSQL_HOST: github-action-runner.famille-suzanne.fr
          MYSQL_TCP_PORT: 3306
        run: mysqladmin --user=root --password=rootpassword drop anyblok_test_${{ github.run_id }}
      - name: Run anyblok_createdb
        env:
          ANYBLOK_DATABASE_DRIVER: mysql
          ANYBLOK_DATABASE_NAME: anyblok_test_${{ github.run_id }}
          ANYBLOK_DATABASE_PORT: 3306
          ANYBLOK_DATABASE_HOST: github-action-runner.famille-suzanne.fr
          ANYBLOK_DATABASE_USER: root
          ANYBLOK_DATABASE_PASSWORD: rootpassword
        run: anyblok_createdb --install-all-bloks  --with-demo
      - name: Run bloks tests
        env:
          ANYBLOK_DATABASE_DRIVER: mysql
          ANYBLOK_DATABASE_NAME: anyblok_test_${{ github.run_id }}
          ANYBLOK_DATABASE_PORT: 3306
          ANYBLOK_DATABASE_HOST: github-action-runner.famille-suzanne.fr
          ANYBLOK_DATABASE_USER: root
          ANYBLOK_DATABASE_PASSWORD: rootpassword
        run: pytest --cov-append anyblok/bloks/anyblok_core
      - name: Generate lcov
        run: coverage-lcov
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: ${{ github.job }}
          path-to-lcov: lcov.info

  finish:
    needs: [Postgres, MySQL]
    runs-on: self-hosted
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          path-to-lcov: lcov.info
